pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-17'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }


        stage('Build & Test') {
            steps {
                dir('services/product-service') {
                    sh 'mvn clean test'
                }
            }
        }


        stage('SonarQube Analysis') {
    steps {
        dir('services/product-service') {
            withSonarQubeEnv('sonarqube-local') {
                sh '''
                  mvn sonar:sonar \
                  -Dsonar.projectKey=product-service \
                  -Dsonar.projectName=product-service
                '''
            }
        }
    }
}

    }



}
