pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-17'
    }

    environment {
        SERVICE_NAME = 'payment-service'
        IMAGE_NAME   = 'suryadasari31/payment-service'
        IMAGE_TAG    = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('services/payment-service') {
                    sh 'mvn clean test'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('services/payment-service') {
                    withSonarQubeEnv('sonarqube-local') {
                        sh """
                          mvn sonar:sonar \
                          -Dsonar.projectKey=${SERVICE_NAME} \
                          -Dsonar.projectName=${SERVICE_NAME}
                        """
                    }
                }
            }
        }

        

        stage('Deploy Artifact to Nexus') {
            steps {
                dir('services/payment-service') {
                    sh 'mvn deploy'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('services/payment-service') {
                    script {
                        dockerImage = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                    }
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh """
                  trivy image \
                  --exit-code 1 \
                  --severity CRITICAL \
                  ${IMAGE_NAME}:${IMAGE_TAG}
                """
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'dockerhub-creds'
                    ) {
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }

        stage('Deploy to Kubernetes (DEV)') {
            steps {
                sh """
                  sed -i 's|IMAGE_TAG|${IMAGE_TAG}|g' k8s/payment-service/deployment.yaml
                  /usr/local/bin/kubectl apply -n dev -f k8s/payment-service/deployment.yaml
                  /usr/local/bin/kubectl apply -n dev -f k8s/payment-service/service.yaml
                  /usr/local/bin/kubectl rollout status deployment/payment-service -n dev
                """
            }
        }
    }

    post {
        failure {
            echo 'Pipeline failed. Image was NOT deployed.'
        }
        success {
            echo 'Pipeline succeeded. Image scanned, pushed, and deployed.'
        }
    }
}
