pipeline {
    agent any

    tools {
        maven 'maven-3'
        jdk 'jdk-17'
    }

    environment {
        IMAGE_NAME = "suryadasari31/user-service"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build & Test') {
            steps {
                dir('services/user-service') {
                    sh 'mvn clean verify'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('services/user-service') {
                    withSonarQubeEnv('sonarqube-local') {
                        sh '''
                          mvn sonar:sonar \
                          -Dsonar.projectKey=user-service \
                          -Dsonar.projectName=user-service
                        '''
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Deploy SNAPSHOT to Nexus') {
            steps {
                dir('services/user-service') {
                    sh 'mvn deploy'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('services/user-service') {
                    script {
                        docker.withRegistry(
                            'https://index.docker.io/v1/',
                            'dockerhub-creds'
                        ) {
                            def app = docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
                            app.push()
                            app.push('latest')
                        }
                    }
                }
            }
        }

        stage('Deploy to Kubernetes (DEV)') {
    steps {
        sh '''
          /usr/local/bin/kubectl apply -n dev -f k8s/user-service/deployment.yaml
          /usr/local/bin/kubectl apply -n dev -f k8s/user-service/service.yaml
          /usr/local/bin/kubectl rollout status deployment/user-service -n dev
        '''
    }
}

            }
        }
    }

    post {
        success {
            echo "Pipeline completed successfully. Application deployed to DEV."
        }
        failure {
            echo "Pipeline failed. Check logs for details."
        }
    }
}
