pipeline {
  agent any

  environment {
    SERVICE_NAME = "orders-service"
    IMAGE_NAME   = "suryadasari31/orders-service"
    IMAGE_TAG    = "1.0.${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build with Maven') {
      steps {
        dir("${SERVICE_NAME}") {
          sh 'mvn clean package -DskipTests'
        }
      }
    }

    stage('Deploy Artifact to Nexus') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'nexus-creds',
          usernameVariable: 'NEXUS_USER',
          passwordVariable: 'NEXUS_PASS'
        )]) {
          dir("${SERVICE_NAME}") {
            sh '''
              mkdir -p ~/.m2

              cat > ~/.m2/settings.xml <<EOF
              <settings>
                <servers>
                  <server>
                    <id>nexus</id>
                    <username>${NEXUS_USER}</username>
                    <password>${NEXUS_PASS}</password>
                  </server>
                </servers>
              </settings>
              EOF

              mvn deploy -DskipTests
            '''
          }
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir("${SERVICE_NAME}") {
          sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
        }
      }
    }

    stage('Docker Push') {
      steps {
        withCredentials([usernamePassword(
          credentialsId: 'dockerhub-creds',
          usernameVariable: 'DOCKER_USER',
          passwordVariable: 'DOCKER_PASS'
        )]) {
          sh """
            echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
            docker push ${IMAGE_NAME_
